# Generated by Django 2.2.3 on 2019-07-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='price',
            new_name='preco',
        ),
    ]
